name: Chicago Beer CPA
favicon: null
layout_spectrum: 0.9523980023805052
typography_spectrum: 0.6841612511780113
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6366160970646888
  lightness: 0.30147609068080783
  saturation: 0.6413028261158615
  rhythmicContrast: 0.6567943841218948
purpose: []
